; ===================== MEASURES 1 =====================

[mGcal1_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal1_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal1_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal1_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal1_IsAllDayTDF]
WeekDateFormat=[mGcal1_IsAllDayWDF]
DynamicVariables=1

[mGcal1_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal1_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal1_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal1_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal1_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 2 =====================

[mGcal2_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal2_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal2_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal2_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal2_IsAllDayTDF]
WeekDateFormat=[mGcal2_IsAllDayWDF]
DynamicVariables=1

[mGcal2_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal2_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal2_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal2_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal2_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 3 =====================

[mGcal3_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal3_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal3_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal3_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal3_IsAllDayTDF]
WeekDateFormat=[mGcal3_IsAllDayWDF]
DynamicVariables=1

[mGcal3_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal3_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal3_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal3_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal3_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 4 =====================

[mGcal4_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal4_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal4_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal4_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal4_IsAllDayTDF]
WeekDateFormat=[mGcal4_IsAllDayWDF]
DynamicVariables=1

[mGcal4_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal4_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal4_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal4_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal4_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 5 =====================

[mGcal5_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal5_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal5_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal5_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal5_IsAllDayTDF]
WeekDateFormat=[mGcal5_IsAllDayWDF]
DynamicVariables=1

[mGcal5_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal5_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal5_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal5_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal5_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 6 =====================

[mGcal6_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal6_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal6_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal6_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal6_IsAllDayTDF]
WeekDateFormat=[mGcal6_IsAllDayWDF]
DynamicVariables=1

[mGcal6_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal6_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal6_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal6_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal6_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 7 =====================

[mGcal7_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal7_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal7_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal7_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal7_IsAllDayTDF]
WeekDateFormat=[mGcal7_IsAllDayWDF]
DynamicVariables=1

[mGcal7_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal7_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal7_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal7_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal7_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 8 =====================

[mGcal8_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal8_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal8_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal8_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal8_IsAllDayTDF]
WeekDateFormat=[mGcal8_IsAllDayWDF]
DynamicVariables=1

[mGcal8_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal8_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal8_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal8_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal8_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 9 =====================

[mGcal9_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal9_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal9_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal9_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal9_IsAllDayTDF]
WeekDateFormat=[mGcal9_IsAllDayWDF]
DynamicVariables=1

[mGcal9_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal9_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal9_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal9_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal9_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 10 =====================

[mGcal10_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal10_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal10_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal10_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal10_IsAllDayTDF]
WeekDateFormat=[mGcal10_IsAllDayWDF]
DynamicVariables=1

[mGcal10_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal10_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal10_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal10_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal10_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 11 =====================

[mGcal11_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal11_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal11_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal11_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal11_IsAllDayTDF]
WeekDateFormat=[mGcal11_IsAllDayWDF]
DynamicVariables=1

[mGcal11_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal11_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal11_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal11_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal11_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 12 =====================

[mGcal12_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal12_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal12_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal12_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal12_IsAllDayTDF]
WeekDateFormat=[mGcal12_IsAllDayWDF]
DynamicVariables=1

[mGcal12_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal12_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal12_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal12_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal12_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 13 =====================

[mGcal13_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal13_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal13_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal13_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal13_IsAllDayTDF]
WeekDateFormat=[mGcal13_IsAllDayWDF]
DynamicVariables=1

[mGcal13_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal13_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal13_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal13_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal13_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 14 =====================

[mGcal14_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal14_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal14_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal14_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal14_IsAllDayTDF]
WeekDateFormat=[mGcal14_IsAllDayWDF]
DynamicVariables=1

[mGcal14_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal14_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal14_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal14_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal14_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 15 =====================

[mGcal15_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal15_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal15_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal15_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal15_IsAllDayTDF]
WeekDateFormat=[mGcal15_IsAllDayWDF]
DynamicVariables=1

[mGcal15_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal15_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal15_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal15_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal15_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 16 =====================

[mGcal16_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal16_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal16_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal16_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal16_IsAllDayTDF]
WeekDateFormat=[mGcal16_IsAllDayWDF]
DynamicVariables=1

[mGcal16_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal16_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal16_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal16_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal16_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 17 =====================

[mGcal17_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal17_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal17_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal17_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal17_IsAllDayTDF]
WeekDateFormat=[mGcal17_IsAllDayWDF]
DynamicVariables=1

[mGcal17_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal17_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal17_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal17_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal17_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 18 =====================

[mGcal18_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal18_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal18_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal18_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal18_IsAllDayTDF]
WeekDateFormat=[mGcal18_IsAllDayWDF]
DynamicVariables=1

[mGcal18_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal18_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal18_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal18_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal18_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 19 =====================

[mGcal19_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal19_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal19_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal19_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal19_IsAllDayTDF]
WeekDateFormat=[mGcal19_IsAllDayWDF]
DynamicVariables=1

[mGcal19_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal19_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal19_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal19_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal19_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 20 =====================

[mGcal20_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal20_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal20_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal20_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal20_IsAllDayTDF]
WeekDateFormat=[mGcal20_IsAllDayWDF]
DynamicVariables=1

[mGcal20_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal20_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal20_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal20_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal20_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 21 =====================

[mGcal21_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal21_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal21_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal21_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal21_IsAllDayTDF]
WeekDateFormat=[mGcal21_IsAllDayWDF]
DynamicVariables=1

[mGcal21_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal21_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal21_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal21_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal21_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 22 =====================

[mGcal22_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal22_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal22_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal22_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal22_IsAllDayTDF]
WeekDateFormat=[mGcal22_IsAllDayWDF]
DynamicVariables=1

[mGcal22_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal22_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal22_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal22_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal22_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 23 =====================

[mGcal23_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal23_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal23_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal23_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal23_IsAllDayTDF]
WeekDateFormat=[mGcal23_IsAllDayWDF]
DynamicVariables=1

[mGcal23_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal23_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal23_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal23_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal23_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 24 =====================

[mGcal24_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal24_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal24_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal24_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal24_IsAllDayTDF]
WeekDateFormat=[mGcal24_IsAllDayWDF]
DynamicVariables=1

[mGcal24_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal24_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal24_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal24_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal24_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 25 =====================

[mGcal25_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal25_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal25_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal25_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal25_IsAllDayTDF]
WeekDateFormat=[mGcal25_IsAllDayWDF]
DynamicVariables=1

[mGcal25_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal25_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal25_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal25_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal25_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 26 =====================

[mGcal26_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal26_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal26_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal26_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal26_IsAllDayTDF]
WeekDateFormat=[mGcal26_IsAllDayWDF]
DynamicVariables=1

[mGcal26_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal26_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal26_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal26_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal26_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 27 =====================

[mGcal27_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal27_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal27_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal27_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal27_IsAllDayTDF]
WeekDateFormat=[mGcal27_IsAllDayWDF]
DynamicVariables=1

[mGcal27_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal27_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal27_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal27_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal27_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 28 =====================

[mGcal28_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal28_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal28_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal28_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal28_IsAllDayTDF]
WeekDateFormat=[mGcal28_IsAllDayWDF]
DynamicVariables=1

[mGcal28_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal28_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal28_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal28_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal28_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 29 =====================

[mGcal29_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal29_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal29_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal29_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal29_IsAllDayTDF]
WeekDateFormat=[mGcal29_IsAllDayWDF]
DynamicVariables=1

[mGcal29_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal29_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal29_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal29_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal29_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 30 =====================

[mGcal30_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal30_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal30_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal30_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal30_IsAllDayTDF]
WeekDateFormat=[mGcal30_IsAllDayWDF]
DynamicVariables=1

[mGcal30_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal30_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal30_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal30_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal30_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 31 =====================

[mGcal31_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal31_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal31_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal31_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal31_IsAllDayTDF]
WeekDateFormat=[mGcal31_IsAllDayWDF]
DynamicVariables=1

[mGcal31_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal31_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal31_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal31_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal31_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 32 =====================

[mGcal32_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal32_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal32_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal32_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal32_IsAllDayTDF]
WeekDateFormat=[mGcal32_IsAllDayWDF]
DynamicVariables=1

[mGcal32_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal32_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal32_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal32_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal32_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 33 =====================

[mGcal33_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal33_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal33_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal33_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal33_IsAllDayTDF]
WeekDateFormat=[mGcal33_IsAllDayWDF]
DynamicVariables=1

[mGcal33_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal33_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal33_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal33_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal33_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 34 =====================

[mGcal34_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal34_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal34_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal34_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal34_IsAllDayTDF]
WeekDateFormat=[mGcal34_IsAllDayWDF]
DynamicVariables=1

[mGcal34_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal34_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal34_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal34_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal34_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 35 =====================

[mGcal35_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal35_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal35_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal35_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal35_IsAllDayTDF]
WeekDateFormat=[mGcal35_IsAllDayWDF]
DynamicVariables=1

[mGcal35_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal35_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal35_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal35_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal35_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 36 =====================

[mGcal36_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal36_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal36_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal36_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal36_IsAllDayTDF]
WeekDateFormat=[mGcal36_IsAllDayWDF]
DynamicVariables=1

[mGcal36_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal36_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal36_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal36_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal36_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 37 =====================

[mGcal37_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal37_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal37_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal37_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal37_IsAllDayTDF]
WeekDateFormat=[mGcal37_IsAllDayWDF]
DynamicVariables=1

[mGcal37_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal37_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal37_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal37_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal37_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 38 =====================

[mGcal38_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal38_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal38_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal38_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal38_IsAllDayTDF]
WeekDateFormat=[mGcal38_IsAllDayWDF]
DynamicVariables=1

[mGcal38_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal38_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal38_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal38_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal38_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 39 =====================

[mGcal39_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal39_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal39_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal39_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal39_IsAllDayTDF]
WeekDateFormat=[mGcal39_IsAllDayWDF]
DynamicVariables=1

[mGcal39_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal39_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal39_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal39_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal39_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 40 =====================

[mGcal40_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal40_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal40_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal40_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal40_IsAllDayTDF]
WeekDateFormat=[mGcal40_IsAllDayWDF]
DynamicVariables=1

[mGcal40_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal40_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal40_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal40_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal40_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 41 =====================

[mGcal41_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal41_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal41_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal41_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal41_IsAllDayTDF]
WeekDateFormat=[mGcal41_IsAllDayWDF]
DynamicVariables=1

[mGcal41_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal41_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal41_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal41_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal41_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 42 =====================

[mGcal42_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal42_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal42_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal42_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal42_IsAllDayTDF]
WeekDateFormat=[mGcal42_IsAllDayWDF]
DynamicVariables=1

[mGcal42_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal42_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal42_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal42_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal42_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 43 =====================

[mGcal43_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal43_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal43_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal43_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal43_IsAllDayTDF]
WeekDateFormat=[mGcal43_IsAllDayWDF]
DynamicVariables=1

[mGcal43_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal43_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal43_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal43_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal43_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 44 =====================

[mGcal44_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal44_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal44_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal44_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal44_IsAllDayTDF]
WeekDateFormat=[mGcal44_IsAllDayWDF]
DynamicVariables=1

[mGcal44_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal44_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal44_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal44_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal44_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 45 =====================

[mGcal45_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal45_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal45_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal45_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal45_IsAllDayTDF]
WeekDateFormat=[mGcal45_IsAllDayWDF]
DynamicVariables=1

[mGcal45_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal45_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal45_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal45_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal45_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 46 =====================

[mGcal46_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal46_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal46_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal46_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal46_IsAllDayTDF]
WeekDateFormat=[mGcal46_IsAllDayWDF]
DynamicVariables=1

[mGcal46_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal46_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal46_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal46_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal46_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 47 =====================

[mGcal47_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal47_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal47_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal47_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal47_IsAllDayTDF]
WeekDateFormat=[mGcal47_IsAllDayWDF]
DynamicVariables=1

[mGcal47_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal47_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal47_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal47_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal47_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 48 =====================

[mGcal48_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal48_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal48_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal48_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal48_IsAllDayTDF]
WeekDateFormat=[mGcal48_IsAllDayWDF]
DynamicVariables=1

[mGcal48_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal48_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal48_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal48_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal48_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 49 =====================

[mGcal49_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal49_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal49_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal49_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal49_IsAllDayTDF]
WeekDateFormat=[mGcal49_IsAllDayWDF]
DynamicVariables=1

[mGcal49_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal49_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal49_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal49_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal49_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


; ===================== MEASURES 50 =====================

[mGcal50_IsAllDayTDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"'all day'","0":"HH:mm"

[mGcal50_IsAllDayWDF]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=IsAllDay
Substitute="1":"ddd 'all day'","0":"ddd HH:mm"

[mGcal50_Title]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal50_Start]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
TodayDateFormat=[mGcal50_IsAllDayTDF]
WeekDateFormat=[mGcal50_IsAllDayWDF]
DynamicVariables=1

[mGcal50_Data@CalId]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal50_Calendar.Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal50_Link]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal

[mGcal50_StartTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=Start
DateFormat=ddd dd MMMMM HH:mm

[mGcal50_EndTooltip]
Measure=Plugin
Plugin=GCal.dll
ParentName=mGcal
Property=End
DateFormat=ddd dd MMMMM HH:mm


