; ===================== METERS 1 =====================

[Item1Bloc]
Meter=Image
MeasureName=mGcal1_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal1_Calendar.Link]"]
MouseActionCursor=1

[Item1Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal1_Title
LeftMouseUpAction=!Execute ["[mGcal1_Link]"]
MouseActionCursor=1

[Item1Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal1_Start
MeasureName2=mGcal1_StartTooltip
MeasureName3=mGcal1_EndTooltip
ToolTipText=%2#CRLF#%3

[Item1Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 2 =====================

[Item2Bloc]
Meter=Image
MeasureName=mGcal2_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal2_Calendar.Link]"]
MouseActionCursor=1

[Item2Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal2_Title
LeftMouseUpAction=!Execute ["[mGcal2_Link]"]
MouseActionCursor=1

[Item2Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal2_Start
MeasureName2=mGcal2_StartTooltip
MeasureName3=mGcal2_EndTooltip
ToolTipText=%2#CRLF#%3

[Item2Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 3 =====================

[Item3Bloc]
Meter=Image
MeasureName=mGcal3_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal3_Calendar.Link]"]
MouseActionCursor=1

[Item3Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal3_Title
LeftMouseUpAction=!Execute ["[mGcal3_Link]"]
MouseActionCursor=1

[Item3Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal3_Start
MeasureName2=mGcal3_StartTooltip
MeasureName3=mGcal3_EndTooltip
ToolTipText=%2#CRLF#%3

[Item3Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 4 =====================

[Item4Bloc]
Meter=Image
MeasureName=mGcal4_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal4_Calendar.Link]"]
MouseActionCursor=1

[Item4Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal4_Title
LeftMouseUpAction=!Execute ["[mGcal4_Link]"]
MouseActionCursor=1

[Item4Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal4_Start
MeasureName2=mGcal4_StartTooltip
MeasureName3=mGcal4_EndTooltip
ToolTipText=%2#CRLF#%3

[Item4Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 5 =====================

[Item5Bloc]
Meter=Image
MeasureName=mGcal5_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal5_Calendar.Link]"]
MouseActionCursor=1

[Item5Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal5_Title
LeftMouseUpAction=!Execute ["[mGcal5_Link]"]
MouseActionCursor=1

[Item5Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal5_Start
MeasureName2=mGcal5_StartTooltip
MeasureName3=mGcal5_EndTooltip
ToolTipText=%2#CRLF#%3

[Item5Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 6 =====================

[Item6Bloc]
Meter=Image
MeasureName=mGcal6_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal6_Calendar.Link]"]
MouseActionCursor=1

[Item6Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal6_Title
LeftMouseUpAction=!Execute ["[mGcal6_Link]"]
MouseActionCursor=1

[Item6Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal6_Start
MeasureName2=mGcal6_StartTooltip
MeasureName3=mGcal6_EndTooltip
ToolTipText=%2#CRLF#%3

[Item6Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 7 =====================

[Item7Bloc]
Meter=Image
MeasureName=mGcal7_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal7_Calendar.Link]"]
MouseActionCursor=1

[Item7Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal7_Title
LeftMouseUpAction=!Execute ["[mGcal7_Link]"]
MouseActionCursor=1

[Item7Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal7_Start
MeasureName2=mGcal7_StartTooltip
MeasureName3=mGcal7_EndTooltip
ToolTipText=%2#CRLF#%3

[Item7Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 8 =====================

[Item8Bloc]
Meter=Image
MeasureName=mGcal8_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal8_Calendar.Link]"]
MouseActionCursor=1

[Item8Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal8_Title
LeftMouseUpAction=!Execute ["[mGcal8_Link]"]
MouseActionCursor=1

[Item8Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal8_Start
MeasureName2=mGcal8_StartTooltip
MeasureName3=mGcal8_EndTooltip
ToolTipText=%2#CRLF#%3

[Item8Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 9 =====================

[Item9Bloc]
Meter=Image
MeasureName=mGcal9_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal9_Calendar.Link]"]
MouseActionCursor=1

[Item9Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal9_Title
LeftMouseUpAction=!Execute ["[mGcal9_Link]"]
MouseActionCursor=1

[Item9Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal9_Start
MeasureName2=mGcal9_StartTooltip
MeasureName3=mGcal9_EndTooltip
ToolTipText=%2#CRLF#%3

[Item9Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 10 =====================

[Item10Bloc]
Meter=Image
MeasureName=mGcal10_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal10_Calendar.Link]"]
MouseActionCursor=1

[Item10Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal10_Title
LeftMouseUpAction=!Execute ["[mGcal10_Link]"]
MouseActionCursor=1

[Item10Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal10_Start
MeasureName2=mGcal10_StartTooltip
MeasureName3=mGcal10_EndTooltip
ToolTipText=%2#CRLF#%3

[Item10Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 11 =====================

[Item11Bloc]
Meter=Image
MeasureName=mGcal11_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal11_Calendar.Link]"]
MouseActionCursor=1

[Item11Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal11_Title
LeftMouseUpAction=!Execute ["[mGcal11_Link]"]
MouseActionCursor=1

[Item11Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal11_Start
MeasureName2=mGcal11_StartTooltip
MeasureName3=mGcal11_EndTooltip
ToolTipText=%2#CRLF#%3

[Item11Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 12 =====================

[Item12Bloc]
Meter=Image
MeasureName=mGcal12_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal12_Calendar.Link]"]
MouseActionCursor=1

[Item12Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal12_Title
LeftMouseUpAction=!Execute ["[mGcal12_Link]"]
MouseActionCursor=1

[Item12Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal12_Start
MeasureName2=mGcal12_StartTooltip
MeasureName3=mGcal12_EndTooltip
ToolTipText=%2#CRLF#%3

[Item12Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 13 =====================

[Item13Bloc]
Meter=Image
MeasureName=mGcal13_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal13_Calendar.Link]"]
MouseActionCursor=1

[Item13Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal13_Title
LeftMouseUpAction=!Execute ["[mGcal13_Link]"]
MouseActionCursor=1

[Item13Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal13_Start
MeasureName2=mGcal13_StartTooltip
MeasureName3=mGcal13_EndTooltip
ToolTipText=%2#CRLF#%3

[Item13Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 14 =====================

[Item14Bloc]
Meter=Image
MeasureName=mGcal14_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal14_Calendar.Link]"]
MouseActionCursor=1

[Item14Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal14_Title
LeftMouseUpAction=!Execute ["[mGcal14_Link]"]
MouseActionCursor=1

[Item14Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal14_Start
MeasureName2=mGcal14_StartTooltip
MeasureName3=mGcal14_EndTooltip
ToolTipText=%2#CRLF#%3

[Item14Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 15 =====================

[Item15Bloc]
Meter=Image
MeasureName=mGcal15_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal15_Calendar.Link]"]
MouseActionCursor=1

[Item15Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal15_Title
LeftMouseUpAction=!Execute ["[mGcal15_Link]"]
MouseActionCursor=1

[Item15Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal15_Start
MeasureName2=mGcal15_StartTooltip
MeasureName3=mGcal15_EndTooltip
ToolTipText=%2#CRLF#%3

[Item15Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 16 =====================

[Item16Bloc]
Meter=Image
MeasureName=mGcal16_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal16_Calendar.Link]"]
MouseActionCursor=1

[Item16Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal16_Title
LeftMouseUpAction=!Execute ["[mGcal16_Link]"]
MouseActionCursor=1

[Item16Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal16_Start
MeasureName2=mGcal16_StartTooltip
MeasureName3=mGcal16_EndTooltip
ToolTipText=%2#CRLF#%3

[Item16Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 17 =====================

[Item17Bloc]
Meter=Image
MeasureName=mGcal17_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal17_Calendar.Link]"]
MouseActionCursor=1

[Item17Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal17_Title
LeftMouseUpAction=!Execute ["[mGcal17_Link]"]
MouseActionCursor=1

[Item17Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal17_Start
MeasureName2=mGcal17_StartTooltip
MeasureName3=mGcal17_EndTooltip
ToolTipText=%2#CRLF#%3

[Item17Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 18 =====================

[Item18Bloc]
Meter=Image
MeasureName=mGcal18_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal18_Calendar.Link]"]
MouseActionCursor=1

[Item18Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal18_Title
LeftMouseUpAction=!Execute ["[mGcal18_Link]"]
MouseActionCursor=1

[Item18Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal18_Start
MeasureName2=mGcal18_StartTooltip
MeasureName3=mGcal18_EndTooltip
ToolTipText=%2#CRLF#%3

[Item18Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 19 =====================

[Item19Bloc]
Meter=Image
MeasureName=mGcal19_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal19_Calendar.Link]"]
MouseActionCursor=1

[Item19Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal19_Title
LeftMouseUpAction=!Execute ["[mGcal19_Link]"]
MouseActionCursor=1

[Item19Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal19_Start
MeasureName2=mGcal19_StartTooltip
MeasureName3=mGcal19_EndTooltip
ToolTipText=%2#CRLF#%3

[Item19Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 20 =====================

[Item20Bloc]
Meter=Image
MeasureName=mGcal20_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal20_Calendar.Link]"]
MouseActionCursor=1

[Item20Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal20_Title
LeftMouseUpAction=!Execute ["[mGcal20_Link]"]
MouseActionCursor=1

[Item20Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal20_Start
MeasureName2=mGcal20_StartTooltip
MeasureName3=mGcal20_EndTooltip
ToolTipText=%2#CRLF#%3

[Item20Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 21 =====================

[Item21Bloc]
Meter=Image
MeasureName=mGcal21_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal21_Calendar.Link]"]
MouseActionCursor=1

[Item21Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal21_Title
LeftMouseUpAction=!Execute ["[mGcal21_Link]"]
MouseActionCursor=1

[Item21Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal21_Start
MeasureName2=mGcal21_StartTooltip
MeasureName3=mGcal21_EndTooltip
ToolTipText=%2#CRLF#%3

[Item21Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 22 =====================

[Item22Bloc]
Meter=Image
MeasureName=mGcal22_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal22_Calendar.Link]"]
MouseActionCursor=1

[Item22Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal22_Title
LeftMouseUpAction=!Execute ["[mGcal22_Link]"]
MouseActionCursor=1

[Item22Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal22_Start
MeasureName2=mGcal22_StartTooltip
MeasureName3=mGcal22_EndTooltip
ToolTipText=%2#CRLF#%3

[Item22Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 23 =====================

[Item23Bloc]
Meter=Image
MeasureName=mGcal23_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal23_Calendar.Link]"]
MouseActionCursor=1

[Item23Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal23_Title
LeftMouseUpAction=!Execute ["[mGcal23_Link]"]
MouseActionCursor=1

[Item23Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal23_Start
MeasureName2=mGcal23_StartTooltip
MeasureName3=mGcal23_EndTooltip
ToolTipText=%2#CRLF#%3

[Item23Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 24 =====================

[Item24Bloc]
Meter=Image
MeasureName=mGcal24_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal24_Calendar.Link]"]
MouseActionCursor=1

[Item24Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal24_Title
LeftMouseUpAction=!Execute ["[mGcal24_Link]"]
MouseActionCursor=1

[Item24Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal24_Start
MeasureName2=mGcal24_StartTooltip
MeasureName3=mGcal24_EndTooltip
ToolTipText=%2#CRLF#%3

[Item24Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 25 =====================

[Item25Bloc]
Meter=Image
MeasureName=mGcal25_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal25_Calendar.Link]"]
MouseActionCursor=1

[Item25Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal25_Title
LeftMouseUpAction=!Execute ["[mGcal25_Link]"]
MouseActionCursor=1

[Item25Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal25_Start
MeasureName2=mGcal25_StartTooltip
MeasureName3=mGcal25_EndTooltip
ToolTipText=%2#CRLF#%3

[Item25Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 26 =====================

[Item26Bloc]
Meter=Image
MeasureName=mGcal26_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal26_Calendar.Link]"]
MouseActionCursor=1

[Item26Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal26_Title
LeftMouseUpAction=!Execute ["[mGcal26_Link]"]
MouseActionCursor=1

[Item26Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal26_Start
MeasureName2=mGcal26_StartTooltip
MeasureName3=mGcal26_EndTooltip
ToolTipText=%2#CRLF#%3

[Item26Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 27 =====================

[Item27Bloc]
Meter=Image
MeasureName=mGcal27_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal27_Calendar.Link]"]
MouseActionCursor=1

[Item27Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal27_Title
LeftMouseUpAction=!Execute ["[mGcal27_Link]"]
MouseActionCursor=1

[Item27Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal27_Start
MeasureName2=mGcal27_StartTooltip
MeasureName3=mGcal27_EndTooltip
ToolTipText=%2#CRLF#%3

[Item27Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 28 =====================

[Item28Bloc]
Meter=Image
MeasureName=mGcal28_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal28_Calendar.Link]"]
MouseActionCursor=1

[Item28Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal28_Title
LeftMouseUpAction=!Execute ["[mGcal28_Link]"]
MouseActionCursor=1

[Item28Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal28_Start
MeasureName2=mGcal28_StartTooltip
MeasureName3=mGcal28_EndTooltip
ToolTipText=%2#CRLF#%3

[Item28Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 29 =====================

[Item29Bloc]
Meter=Image
MeasureName=mGcal29_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal29_Calendar.Link]"]
MouseActionCursor=1

[Item29Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal29_Title
LeftMouseUpAction=!Execute ["[mGcal29_Link]"]
MouseActionCursor=1

[Item29Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal29_Start
MeasureName2=mGcal29_StartTooltip
MeasureName3=mGcal29_EndTooltip
ToolTipText=%2#CRLF#%3

[Item29Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 30 =====================

[Item30Bloc]
Meter=Image
MeasureName=mGcal30_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal30_Calendar.Link]"]
MouseActionCursor=1

[Item30Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal30_Title
LeftMouseUpAction=!Execute ["[mGcal30_Link]"]
MouseActionCursor=1

[Item30Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal30_Start
MeasureName2=mGcal30_StartTooltip
MeasureName3=mGcal30_EndTooltip
ToolTipText=%2#CRLF#%3

[Item30Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 31 =====================

[Item31Bloc]
Meter=Image
MeasureName=mGcal31_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal31_Calendar.Link]"]
MouseActionCursor=1

[Item31Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal31_Title
LeftMouseUpAction=!Execute ["[mGcal31_Link]"]
MouseActionCursor=1

[Item31Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal31_Start
MeasureName2=mGcal31_StartTooltip
MeasureName3=mGcal31_EndTooltip
ToolTipText=%2#CRLF#%3

[Item31Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 32 =====================

[Item32Bloc]
Meter=Image
MeasureName=mGcal32_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal32_Calendar.Link]"]
MouseActionCursor=1

[Item32Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal32_Title
LeftMouseUpAction=!Execute ["[mGcal32_Link]"]
MouseActionCursor=1

[Item32Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal32_Start
MeasureName2=mGcal32_StartTooltip
MeasureName3=mGcal32_EndTooltip
ToolTipText=%2#CRLF#%3

[Item32Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 33 =====================

[Item33Bloc]
Meter=Image
MeasureName=mGcal33_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal33_Calendar.Link]"]
MouseActionCursor=1

[Item33Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal33_Title
LeftMouseUpAction=!Execute ["[mGcal33_Link]"]
MouseActionCursor=1

[Item33Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal33_Start
MeasureName2=mGcal33_StartTooltip
MeasureName3=mGcal33_EndTooltip
ToolTipText=%2#CRLF#%3

[Item33Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 34 =====================

[Item34Bloc]
Meter=Image
MeasureName=mGcal34_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal34_Calendar.Link]"]
MouseActionCursor=1

[Item34Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal34_Title
LeftMouseUpAction=!Execute ["[mGcal34_Link]"]
MouseActionCursor=1

[Item34Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal34_Start
MeasureName2=mGcal34_StartTooltip
MeasureName3=mGcal34_EndTooltip
ToolTipText=%2#CRLF#%3

[Item34Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 35 =====================

[Item35Bloc]
Meter=Image
MeasureName=mGcal35_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal35_Calendar.Link]"]
MouseActionCursor=1

[Item35Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal35_Title
LeftMouseUpAction=!Execute ["[mGcal35_Link]"]
MouseActionCursor=1

[Item35Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal35_Start
MeasureName2=mGcal35_StartTooltip
MeasureName3=mGcal35_EndTooltip
ToolTipText=%2#CRLF#%3

[Item35Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 36 =====================

[Item36Bloc]
Meter=Image
MeasureName=mGcal36_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal36_Calendar.Link]"]
MouseActionCursor=1

[Item36Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal36_Title
LeftMouseUpAction=!Execute ["[mGcal36_Link]"]
MouseActionCursor=1

[Item36Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal36_Start
MeasureName2=mGcal36_StartTooltip
MeasureName3=mGcal36_EndTooltip
ToolTipText=%2#CRLF#%3

[Item36Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 37 =====================

[Item37Bloc]
Meter=Image
MeasureName=mGcal37_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal37_Calendar.Link]"]
MouseActionCursor=1

[Item37Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal37_Title
LeftMouseUpAction=!Execute ["[mGcal37_Link]"]
MouseActionCursor=1

[Item37Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal37_Start
MeasureName2=mGcal37_StartTooltip
MeasureName3=mGcal37_EndTooltip
ToolTipText=%2#CRLF#%3

[Item37Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 38 =====================

[Item38Bloc]
Meter=Image
MeasureName=mGcal38_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal38_Calendar.Link]"]
MouseActionCursor=1

[Item38Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal38_Title
LeftMouseUpAction=!Execute ["[mGcal38_Link]"]
MouseActionCursor=1

[Item38Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal38_Start
MeasureName2=mGcal38_StartTooltip
MeasureName3=mGcal38_EndTooltip
ToolTipText=%2#CRLF#%3

[Item38Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 39 =====================

[Item39Bloc]
Meter=Image
MeasureName=mGcal39_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal39_Calendar.Link]"]
MouseActionCursor=1

[Item39Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal39_Title
LeftMouseUpAction=!Execute ["[mGcal39_Link]"]
MouseActionCursor=1

[Item39Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal39_Start
MeasureName2=mGcal39_StartTooltip
MeasureName3=mGcal39_EndTooltip
ToolTipText=%2#CRLF#%3

[Item39Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 40 =====================

[Item40Bloc]
Meter=Image
MeasureName=mGcal40_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal40_Calendar.Link]"]
MouseActionCursor=1

[Item40Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal40_Title
LeftMouseUpAction=!Execute ["[mGcal40_Link]"]
MouseActionCursor=1

[Item40Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal40_Start
MeasureName2=mGcal40_StartTooltip
MeasureName3=mGcal40_EndTooltip
ToolTipText=%2#CRLF#%3

[Item40Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 41 =====================

[Item41Bloc]
Meter=Image
MeasureName=mGcal41_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal41_Calendar.Link]"]
MouseActionCursor=1

[Item41Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal41_Title
LeftMouseUpAction=!Execute ["[mGcal41_Link]"]
MouseActionCursor=1

[Item41Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal41_Start
MeasureName2=mGcal41_StartTooltip
MeasureName3=mGcal41_EndTooltip
ToolTipText=%2#CRLF#%3

[Item41Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 42 =====================

[Item42Bloc]
Meter=Image
MeasureName=mGcal42_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal42_Calendar.Link]"]
MouseActionCursor=1

[Item42Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal42_Title
LeftMouseUpAction=!Execute ["[mGcal42_Link]"]
MouseActionCursor=1

[Item42Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal42_Start
MeasureName2=mGcal42_StartTooltip
MeasureName3=mGcal42_EndTooltip
ToolTipText=%2#CRLF#%3

[Item42Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 43 =====================

[Item43Bloc]
Meter=Image
MeasureName=mGcal43_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal43_Calendar.Link]"]
MouseActionCursor=1

[Item43Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal43_Title
LeftMouseUpAction=!Execute ["[mGcal43_Link]"]
MouseActionCursor=1

[Item43Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal43_Start
MeasureName2=mGcal43_StartTooltip
MeasureName3=mGcal43_EndTooltip
ToolTipText=%2#CRLF#%3

[Item43Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 44 =====================

[Item44Bloc]
Meter=Image
MeasureName=mGcal44_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal44_Calendar.Link]"]
MouseActionCursor=1

[Item44Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal44_Title
LeftMouseUpAction=!Execute ["[mGcal44_Link]"]
MouseActionCursor=1

[Item44Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal44_Start
MeasureName2=mGcal44_StartTooltip
MeasureName3=mGcal44_EndTooltip
ToolTipText=%2#CRLF#%3

[Item44Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 45 =====================

[Item45Bloc]
Meter=Image
MeasureName=mGcal45_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal45_Calendar.Link]"]
MouseActionCursor=1

[Item45Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal45_Title
LeftMouseUpAction=!Execute ["[mGcal45_Link]"]
MouseActionCursor=1

[Item45Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal45_Start
MeasureName2=mGcal45_StartTooltip
MeasureName3=mGcal45_EndTooltip
ToolTipText=%2#CRLF#%3

[Item45Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 46 =====================

[Item46Bloc]
Meter=Image
MeasureName=mGcal46_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal46_Calendar.Link]"]
MouseActionCursor=1

[Item46Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal46_Title
LeftMouseUpAction=!Execute ["[mGcal46_Link]"]
MouseActionCursor=1

[Item46Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal46_Start
MeasureName2=mGcal46_StartTooltip
MeasureName3=mGcal46_EndTooltip
ToolTipText=%2#CRLF#%3

[Item46Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 47 =====================

[Item47Bloc]
Meter=Image
MeasureName=mGcal47_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal47_Calendar.Link]"]
MouseActionCursor=1

[Item47Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal47_Title
LeftMouseUpAction=!Execute ["[mGcal47_Link]"]
MouseActionCursor=1

[Item47Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal47_Start
MeasureName2=mGcal47_StartTooltip
MeasureName3=mGcal47_EndTooltip
ToolTipText=%2#CRLF#%3

[Item47Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 48 =====================

[Item48Bloc]
Meter=Image
MeasureName=mGcal48_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal48_Calendar.Link]"]
MouseActionCursor=1

[Item48Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal48_Title
LeftMouseUpAction=!Execute ["[mGcal48_Link]"]
MouseActionCursor=1

[Item48Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal48_Start
MeasureName2=mGcal48_StartTooltip
MeasureName3=mGcal48_EndTooltip
ToolTipText=%2#CRLF#%3

[Item48Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 49 =====================

[Item49Bloc]
Meter=Image
MeasureName=mGcal49_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal49_Calendar.Link]"]
MouseActionCursor=1

[Item49Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal49_Title
LeftMouseUpAction=!Execute ["[mGcal49_Link]"]
MouseActionCursor=1

[Item49Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal49_Start
MeasureName2=mGcal49_StartTooltip
MeasureName3=mGcal49_EndTooltip
ToolTipText=%2#CRLF#%3

[Item49Bar]
Meter=Image
MeterStyle=sSeperator

; ===================== METERS 50 =====================

[Item50Bloc]
Meter=Image
MeasureName=mGcal50_Data@CalId
ImageName=cal%1.png
MeterStyle=sColorBloc
LeftMouseUpAction=!Execute ["[mGcal50_Calendar.Link]"]
MouseActionCursor=1

[Item50Left]
Meter=String
MeterStyle=sTextL
MeasureName=mGcal50_Title
LeftMouseUpAction=!Execute ["[mGcal50_Link]"]
MouseActionCursor=1

[Item50Right]
Meter=String
MeterStyle=sTextR
MeasureName=mGcal50_Start
MeasureName2=mGcal50_StartTooltip
MeasureName3=mGcal50_EndTooltip
ToolTipText=%2#CRLF#%3

[Item50Bar]
Meter=Image
MeterStyle=sSeperator

